"""Build Results/comparison.md (paper vs original Stata code vs StatsPAI) from the CSV outputs.

Run after replicate_tables.py, replicate_figures.py, extensions.py:
    /usr/local/bin/python3.13 Program/statspai/make_comparison.py
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

from common import AUTHOR, OUT, ROOT, STATA_TABLES

MD = []


def w(s=""):
    MD.append(s)


def fmt(x, d=3):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return ""
    return f"{x:.{d}f}"


def main():
    steps = pd.read_csv(ROOT / "Results" / "run_original_steps.csv")
    steps.columns = [c.strip() for c in steps.columns]
    partial = ROOT / "Results" / "run_original_steps_partial.csv"
    tab = pd.read_csv(OUT / "main_tables_long.csv")
    figs = pd.read_csv(OUT / "figures_check.csv")

    # ------------------------------------------------------------ text-output diff of every author .txt
    diffs = {}
    for f in sorted(AUTHOR.glob("*.txt")):
        g = STATA_TABLES / f.name
        if not g.exists():
            diffs[f.name] = "not produced by current code"
            continue
        a = [l.rstrip("\r\n") for l in open(f, encoding="latin-1")]
        b = [l.rstrip("\r\n") for l in open(g, encoding="latin-1")]
        nd = sum(x != y for x, y in zip(a, b)) + abs(len(a) - len(b))
        diffs[f.name] = "identical" if nd == 0 else f"{nd} line(s) differ"

    w("# Replication comparison — Bai, Jia & Yang (2023, QJE) “Web of Power”")
    w()
    w("*Generated by `Program/statspai/make_comparison.py`.*  ")
    w("**Paper values** = the authors' own outputs shipped in the package (`Results/author_outputs/*.txt`, "
      "produced 13 Oct 2022 by `All_in_One.do`), cross-checked against the tables of NBER WP 28667 "
      "(revised Aug 2022 = the accepted version; the QJE PDF itself is paywalled). Where the WP table differs from the "
      "author output the WP number is used and flagged.  ")
    w("**Original Stata** = our rerun of the package in Stata 18 MP (`Program/run_original.do`, "
      "`Results/Tables/*.txt`).  **StatsPAI** = `Program/statspai/replicate_tables.py` / `replicate_figures.py` "
      "(StatsPAI 1.28.0, Python 3.13).  ")
    w("Status: ✅ identical at reported precision (3 decimals, N) · ⚠️ small difference, explained · ❌ failure.")
    w()
    w("Figure numbering follows the package / NBER WP (Figure 3 … 8). In the published QJE article the same figures "
      "are numbered one higher (Figure IV … IX), as also noted by the I4R comment (Buchot et al. 2024).")
    w()

    # ------------------------------------------------------------ overview
    w("## 1. Overview")
    w()
    w("| Exhibit | Original code (Stata 18) | rc | sec | vs. paper | StatsPAI | vs. paper |")
    w("|---|---|---:|---:|---|---|---|")
    stat_by_table = tab.groupby("table").status.agg(lambda s: "✅" if (s == "✅").all() else ("❌" if (s == "❌").any() else "⚠️"))
    exhibit_rows = [
        ("Table 1 Summary statistics", "Table_1", "✅ (log identical)", "✅ all moments (see §2.1)", "✅"),
        ("Table 2 DD soldier deaths", "Table_2", "✅ identical", None, stat_by_table.get("Table 2")),
        ("Table 3 Types of links / surnames", "Table_3", "⚠️ identical to author output; N 1,110 vs 1,125 printed", None,
         stat_by_table.get("Table 3")),
        ("Table 4 Placebo networks / IV / Huai", "Table_4", "⚠️ 3 IV SEs differ by 0.001 (ivreghdfe dof)", None,
         stat_by_table.get("Table 4")),
        ("Table 5 DD/DDD elite power", "Table_5", "✅ identical", None, stat_by_table.get("Table 5")),
        ("Table 6 Role of soldier deaths (OLS/IV)", "Table_6", "✅ identical", None, stat_by_table.get("Table 6")),
        ("Figure 3 Raw soldier deaths", "Figure_3", "✅ tabout identical", "✅ 30 means (≤5e-4 = rounding)", "✅"),
        ("Figure 4 Year-by-year soldier deaths", "Figure_4", "✅ outreg2/parmest identical", "✅ 56 coefs+SEs ≤3e-8", "✅"),
        ("Figure 5 Raw national offices", "Figure_5", "✅ tabout identical", "✅ 364 means (≤5e-4 = rounding)", "✅"),
        ("Figure 6 Year-by-year power effect", "Figure_6", "✅ parmest identical", "✅ 360 coefs+SEs ≤1e-8", "✅"),
        ("Figure 7 EG index", "Figure_7", "✅ graph; Table C7 decade means identical", "✅ decade means = Stata to 7 d.p.", "✅"),
        ("Figure 8 Provincial governors", "Figure_8", "✅ graph", "✅ ratios + fitted line re-drawn", "✅"),
    ]
    st = steps.set_index("step")
    for name, step, orig, sp_desc, sp_stat in exhibit_rows:
        rc = int(st.loc[step, "rc"]) if step in st.index else ""
        sec = fmt(float(st.loc[step, "seconds"]), 1) if step in st.index else ""
        if sp_desc is None:
            sub = tab[tab.table == name.split(" ")[0] + " " + name.split(" ")[1]]
            same = int(((sub.abs_diff_coef_vs_stata == 0) & (sub.abs_diff_se_vs_stata == 0) & (sub.N == sub.stata_N)).sum())
            sp_desc = f"{same}/{len(sub)} coef·SE·N cells = Stata rerun; {(sub.status == '✅').sum()}/{len(sub)} = paper"
        w(f"| {name} | {orig} | {rc} | {sec} | {'✅' if orig.startswith('✅') else '⚠️'} | {sp_desc} | {sp_stat} |")
    w()
    w("Appendix exhibits (original code only; StatsPAI re-implementation covers the main text + extensions):")
    w()
    w("| Do-file | rc | sec | author .txt output vs. our rerun | status |")
    w("|---|---:|---:|---|---|")
    app_txt = {
        "Appendix_Table_A3": ["Appendix_Table_A3.txt"], "Appendix_Figure_A5": [], "Appendix_Table_B1_I": ["Appendix_Table_B1_I.txt"],
        "Appendix_Table_B1_II": ["Appendix_Table_B1_II.txt"],
        "Appendix_Table_B1_III": ["Appendix_Table_B1_III_50KM.txt", "Appendix_Table_B1_III_100KM.txt", "Appendix_Table_B1_III_200KM.txt"],
        "Appendix_Table_B1_IV": ["Appendix_Table_B1_IV.txt"], "Appendix_Table_B2": ["Appendix_Table_B2.txt"],
        "Appendix_Table_B4": ["Appendix_Table_B4.txt"], "Appendix_Table_B5_I": ["Appendix_Table_B5_I.txt"],
        "Appendix_Table_B5_II": ["Appendix_Table_B5_II.txt"], "Appendix_Table_B6_I": ["Appendix_Table_B6_I.txt"],
        "Appendix_Table_B6_II": ["Appendix_Table_B6_II.txt"], "Appendix_Figure_C1": [], "Appendix_Table_C2": ["Appendix_Table_C2.txt"],
        "Appendix_Table_C3": ["Appendix_Table_C3.txt"], "Appendix_Table_C4": ["Appendix_Table_C4.txt"],
        "Appendix_Table_C5": ["Appendix_Table_C5.txt"], "Appendix_Table_C6": ["Appendix_Table_C6.txt"], "Appendix_Table_C7": [],
    }
    for step, files in app_txt.items():
        rc = int(st.loc[step, "rc"])
        sec = fmt(float(st.loc[step, "seconds"]), 1)
        if files:
            desc = "; ".join(f"{f}: {diffs.get(f, '?')}" for f in files)
            ok = all(diffs.get(f) == "identical" for f in files)
        else:
            desc = "graph / log table only (no .txt) — ran, output inspected"
            ok = True
        note = ""
        if step == "Appendix_Table_B1_III":
            sec = "22.7"
            note = " (re-run alone via `global ONLY` after installing the original 2015 `reg2hdfespatial` with Bartlett kernel; the newer GitHub version gives SEs ~7% larger)"
        w(f"| {step} | {rc} | {sec} | {desc}{note} | {'✅' if ok else '⚠️'} |")
    w()
    w(f"Total Stata runtime: {steps.seconds.sum():.0f} s (≈{steps.seconds.sum() / 60:.1f} min) for 31 do-files, all rc = 0. "
      "Leftover author files not produced by the current code: `Table_4b.txt` (= Table 4 cols 7–11, now appended to "
      "`Table_4.txt`) and `Appendix_Table_B6.txt` (= B6.I cols 4–5, now appended to `Appendix_Table_B6_I.txt`); both "
      "match the corresponding columns.")
    w()

    # ------------------------------------------------------------ Table 1
    w("## 2. Main tables, number by number")
    w()
    w("### 2.1 Table 1 (selected moments; full output in `Results/statspai/table1.csv`)")
    w()
    t1 = pd.read_csv(OUT / "table1.csv")
    t1 = t1[t1.paper_mean.notna()]
    w("| Panel | Variable | N | paper mean | StatsPAI mean | paper s.d. | StatsPAI s.d. | status |")
    w("|---|---|---:|---:|---:|---:|---:|---|")
    for _, r in t1.iterrows():
        scale = 1000 if r["var"] == "martyrs_tot_hn" else 1
        ok = abs(round(r["mean"] / scale, 2) - r.paper_mean / scale) < 1e-9 and abs(round(r["std"] / scale, 2) - r.paper_sd / scale) < 1e-9
        stat = "✅" if ok else "⚠️"
        w(f"| {r.panel} | {r['var']} | {int(r['count']):,} | {r.paper_mean / scale:.2f} | {r['mean'] / scale:.3f} | "
          f"{r.paper_sd / scale:.2f} | {r['std'] / scale:.3f} | {stat} |")
    w()
    w("Notes: `martyrs_tot_hn` in thousands. ⚠️ Panel A `Zeng_all0_invdist_pc` mean: the paper prints 4.48, but the "
      "data (and the authors' own log) give 4.458 → a typo in the published table. Panel B is labelled 1820–1910 "
      "(N = 149,786) but `Table_1.do` summarises all 1800–1910 rows (N = 182,706); the time-invariant moments are "
      "unaffected (also noted by I4R).")
    w()
    for t in ["Table 2", "Table 3", "Table 4", "Table 5", "Table 6"]:
        sub = tab[tab.table == t]
        w(f"### 2.{int(t[-1])} {t}")
        w()
        w("| col | variable | paper b (se) | N | Stata rerun b (se) | N | StatsPAI b (se) | N | |Δb|,|Δse| vs Stata | status |")
        w("|---:|---|---|---:|---|---:|---|---:|---|---|")
        for _, r in sub.iterrows():
            pN = "" if pd.isna(r.paper_N) else f"{int(r.paper_N):,}"
            sN = "" if pd.isna(r.stata_N) else f"{int(r.stata_N):,}"
            w(f"| {r.col} | `{r['var']}` | {fmt(r.paper_coef)} ({fmt(r.paper_se)}) | {pN} | {fmt(r.stata_coef)} ({fmt(r.stata_se)}) | "
              f"{sN} | {r.coef:.4f} ({r.se:.4f}) | {int(r.N):,} | {r.abs_diff_coef_vs_stata:.3f}, {r.abs_diff_se_vs_stata:.3f} | {r.status} |")
        w()
        if t == "Table 3":
            w("⚠️ explained: (i) cols 1–4 — current `reghdfe` drops 15 singleton county-years (prefecture×year cells "
              "with one county); the published table prints N = 1,125 while the authors' own 2022 log already shows "
              "1,110 — coefficients/SEs are unaffected at 3 d.p. (I4R note). (ii) col 6 — the NBER/QJE table prints the "
              "different-surname coefficient as 0.057 (0.016); the authors' code/log and both our runs give 0.056 (0.017): "
              "a transcription difference in the paper.")
            w()
        if t == "Table 4":
            w("⚠️ explained: IV columns 4–6 — the authors' 2022 `ivreghdfe` counted one more absorbed degree of freedom "
              "than current `ivreghdfe` (their log: SE .1374985 vs our .1374197 for col 4), which moves three placebo SEs "
              "by 0.001. StatsPAI matches the current ivreghdfe exactly; adding one dof (`iv(..., extra_dof=1)`) reproduces "
              "the published SEs.")
            w()

    # ------------------------------------------------------------ figures
    w("## 3. Figures (numerical content)")
    w()
    w("| Figure | quantity | n | max |StatsPAI − author output| | status |")
    w("|---|---|---:|---:|---|")
    for _, r in figs.iterrows():
        stat = "✅" if r.max_abs_diff < 1e-3 else "⚠️"
        w(f"| {r.figure} | {r.quantity} | {r.n} | {r.max_abs_diff:.2e} | {stat} |")
    w()
    eg = pd.read_csv(OUT / "tableC7_eg_by_decade.csv")
    stata_c7 = [(0.0096787, 0.0097987), (0.0110766, 0.0111667), (0.0139749, 0.014309), (0.0149146, 0.0149491),
                (0.0289491, 0.014056), (0.0261659, 0.0206211), (0.0357897, 0.0243134), (0.0292151, 0.0255431),
                (0.0229293, 0.0225314), (0.0204327, 0.0204333)]
    w("Figure 7 / Table C7 — EG index by decade (Stata log vs StatsPAI):")
    w()
    w("| decade | EG (Stata) | EG (StatsPAI) | EG w/o Hunan×connections (Stata) | (StatsPAI) |")
    w("|---|---:|---:|---:|---:|")
    for (_, r), (a, b) in zip(eg.iterrows(), stata_c7):
        w(f"| {int(r.dec)}0s | {a:.7f} | {r.gamaalloff:.7f} | {b:.7f} | {r.gamaalloff_NoConn:.7f} |")
    w()
    w("Paper text: EG rises from 0.015 (1850s) to 0.036 (1880s); counterfactual 0.024 → networks explain 57% — reproduced "
      f"((0.0358−0.0243)/(0.0358−0.0149) = {(0.0357897 - 0.0243134) / (0.0357897 - 0.0149146):.0%}; the paper computes "
      "(0.036−0.024)/(0.036−0.015) = 57%).")
    w()
    w("Figures are re-drawn in `Results/statspai/figure{3..8}.png`; Stata versions in `Results/Figures/`, author PNGs in "
      "`Results/author_outputs/`.")
    w()

    # ------------------------------------------------------------ StatsPAI issue record
    w("## 4. StatsPAI `hdfe_ols` issue record")
    w()
    iss = pd.read_csv(OUT / "statspai_hdfe_ols_issue.csv")
    w("| regression | var | Stata b (se) | sp.hdfe_ols b (se) | iters | dof_fe | sp.feols + reghdfe dof b (se) |")
    w("|---|---|---|---|---:|---:|---|")
    for _, r in iss.iterrows():
        w(f"| {r.regression} | `{r['var']}` | {fmt(r.stata_coef, 5)} ({fmt(r.stata_se, 5)}) | {r.hdfe_ols_coef:.5f} ({r.hdfe_ols_se:.5f}) | "
          f"{r.hdfe_ols_iters} | {r.hdfe_ols_dof_fe} | {r.feols_reghdfe_coef:.5f} ({r.feols_reghdfe_se:.5f}) |")
    w()
    w("With `year` nested in `prefidXyear`, `sp.hdfe_ols` over-counts absorbed dof by 14 (SEs ≈0.8% too large). In the Huai "
      "columns it also keeps two controls (`lncntypop_Post`, `lncntyarea_Post`) that are collinear with prefecture×year FEs up "
      "to float32 noise — Stata/pyfixest omit them — giving coefficients of ±4.8e5 and moving the coefficient of interest by 8%. "
      "Therefore all one-way-clustered regressions use `sp.feols` (pyfixest backend) + reghdfe's dof formula.")
    w()

    # ------------------------------------------------------------ extensions
    w("## 5. Modern-methods extensions (NOT replication)")
    w()
    p = OUT / "ext_E1_conley.csv"
    if p.exists():
        e1 = pd.read_csv(p)
        w("### E1 Conley spatial-serial HAC: `sp.conley` vs authors' `reg2hdfespatial` (Table B.1.III)")
        w()
        w("| spec | cutoff | kernel | b | sp.conley SE | Stata reg2hdfespatial SE |")
        w("|---|---:|---|---:|---:|---:|")
        for _, r in e1.iterrows():
            w(f"| {r.spec} | {r.cutoff_km} km | {r.spatial_kernel} | {r.coef:.3f} | {r.conley_se:.4f} | {fmt(r.stata_reg2hdfespatial_se)} |")
        w()
    p = OUT / "ext_E2_wild_bootstrap.csv"
    if p.exists():
        e2 = pd.read_csv(p)
        w("### E2 Wild cluster bootstrap with few (prefecture) clusters")
        w()
        w("| regression | G | b | CR1 SE | p (t, G−1) | weights | sp.hdfe_ols(wild=True) p ❌ | corrected WCR p | Stata boottest p |")
        w("|---|---:|---:|---:|---:|---|---:|---:|---:|")
        for _, r in e2.iterrows():
            w(f"| {r.regression} | {r.n_clusters} | {r.coef:.3f} | {r.cluster_se:.3f} | {r.cluster_p_tG1:.3f} | {r.wild_weights} | "
              f"{r.sp_hdfe_ols_wild_p:.3f} | {r.corrected_wcr_p:.3f} | {fmt(r.stata_boottest_p)} |")
        w()
        w("`sp.hdfe_ols(wild=True)` does not re-absorb the fixed effects in each bootstrap draw; with `year` FE not nested in "
          "prefecture clusters its p-values are too small (e.g. Table 5 col 1: 0.05 vs 0.22–0.23). The corrected WCR "
          "(`extensions.wcr_fe`) agrees with Stata `boottest` (`Program/statspai/crosscheck_boottest.do`) up to Monte-Carlo error.")
        w()
    p = OUT / "ext_E3_pretrends.json"
    if p.exists():
        e3 = json.load(open(p))
        w("### E3 Event-study diagnostics for Figure 4A (weighted connections × year)")
        w()
        w("```json")
        w(json.dumps(e3, indent=1, default=str)[:4000])
        w("```")
        w()
        for f, title in [("ext_E3_honestdid_statspai.csv", "StatsPAI honest_did (native / R backend; diagonal covariance)"),
                         ("ext_E3_honestdid_R_fullvcov.csv", "R HonestDiD with the FULL event-study covariance (benchmark)")]:
            q = OUT / f
            if q.exists():
                d = pd.read_csv(q)
                w(f"{title}:")
                w()
                w(d.to_markdown(index=False, floatfmt=".4f"))
                w()
    for f, title in [("ext_E4_continuous_did.csv", "E4 Continuous-treatment DID"),
                     ("ext_E5_functional_form.csv", "E5 Functional form with many zeros (Chen & Roth 2024)"),
                     ("ext_E7_weak_iv_table4.csv", "E7 Weak-IV robust inference, Table 4 IV columns")]:
        q = OUT / f
        if q.exists():
            w(f"### {title}")
            w()
            w(pd.read_csv(q).to_markdown(index=False, floatfmt=".4f"))
            w()
    q = OUT / "ext_E6_national_ddd_pretrends.json"
    if q.exists():
        w("### E6 Joint pre-trend tests, national DDD event study (Figure 6C, 1821–1853 coefficients)")
        w()
        w("```json")
        w(json.dumps(json.load(open(q)), indent=1))
        w("```")
        w()
    (ROOT / "Results" / "comparison.md").write_text("\n".join(MD), encoding="utf-8")
    print("wrote comparison.md", len(MD), "lines")


if __name__ == "__main__":
    main()
